src/user/urls.py
from django.urls import path
from .views import index_user, add_user, update_user, delete_user

app_name = 'user'

urlpatterns = [
    path('', index_user, name='index'),
    path('add-user', add_user, name='add'),
    path('update-user/<int:id>', update_user, name='update'),
    path('delete-user/<int:id>', delete_user, name='delete'),
] 

src/webSite/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import login

urlpatterns = [
    path('', login, name='login'), 
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')), 
    path('student/', include('student.urls')), 
    path('teacher/', include('teacher.urls')), 
    path('user/', include('user.urls')), 
]

src/user/models.py
from django.db import models

# Create your models here.

class UserModel(models.Model):
    pseudo = models.CharField(max_length=15, unique=True)
    password = models.CharField(max_length=128)
    date_creation = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.pseudo

    class Meta:
        ordering = ['-id']
        verbose_name = 'Utilisateur'
        verbose_name_plural = 'Utilisateurs'

src/user/forms.py
from django import forms
from .models import UserModel

# class UserForm(forms.Form):
#     pseudo = forms.CharField(label="Pseudo", max_length=15, strip=True, required=True)
#     password = forms.CharField(label="Mot de passe",min_length=8, widget= forms.PasswordInput(), required=True)
#     password_confirm = forms.CharField(label="Confirmation du mot de passe",min_length=8, widget= forms.PasswordInput(), required=True)

#     def clean_password(self):
#         password = self.cleaned_data.get('password') 
#         password_confirm = self.cleaned_data.get('password_confirm') 

#         forbidden_characters = ['$', '&', '#', '{', '[', '£']
#         if any(char in password for char in forbidden_characters): 
#             raise forms.ValidationError("Le mot de pass ne doit pas contenir les valeurs suivant: '&', '#', '{', '[','£','$' ") 

#         if password and password_confirm and password != password_confirm:
#             raise forms.ValidationError("Les mots de passe ne correspondent pas.")
#         return password
 
class UserForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ["pseudo", "password"]

        widgets = {
            'pseudo': forms.TextInput(attrs={'placeholder': 'Prénom'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Password'}),
        }

src/user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.hashers import make_password

from .forms import UserForm
from .models import UserModel

# Create your views here.

def index_user(request):
    user_list =  UserModel.objects.all()

    paginator = Paginator(user_list, 10)  
    page_number = request.GET.get('page')
    users = paginator.get_page(page_number)

    context = {
        'users': users
    }
    return render(request, "user/index.html", context) 

# def add(request):
#     if request.method == "POST":
#         form = UserForm(request.POST)
#         if form.is_valid():
#             User.objects.create(
#                 pseudo=form.cleaned_data['pseudo'],
#                 password=make_password(form.cleaned_data['password'])
#                 )
#             return redirect("user:index")
#     else:
#         form = UserForm()

#     return render(request, "user/add_user.html", {'form': form}) 

def add_user(request):
    context = {
        'title': 'Ajouter utilisateur',
        'submit_value': 'Ajouter'
    }

    if request.method == "POST":
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            print(user_form.cleaned_data)
            user = user_form.save(commit=False)
            user.password = make_password(user_form.cleaned_data['password']) 
            user_form.save()
            messages.success(request, "L'utilisateur a été ajouté avec succès.")
            return redirect("user:index")
        else:
            print("formulaire erroné")
            messages.error(request, "Erreur dans le formulaire. Veuillez vérifier les champs.")
            

    user_form = UserForm()
    context['form'] = user_form

    return render(request, "user/add_user.html", context)

def update_user(request, id):
    user = UserModel.objects.get(id = id)
    context = {
        'title': 'Modifier l\'utilisateur',
        'submit_value': 'Modifier'
    }
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=user)
        if user_form.is_valid():    
            user = user_form.save(commit=False)
            user.password = make_password(user_form.cleaned_data['password']) 
            user_form.save()
            messages.success(request, "L'utilisateur a été ajouté avec succès.")
            return redirect("user:index")
        else:
            print("formulaire erroné")
            messages.error(request, "Erreur dans le formulaire. Veuillez vérifier les champs.")


    user_form = UserForm(instance=user)
    context['form'] = user_form

    return render(request, "user/add_user.html", context) 

def delete_user(request, id):
    user = get_object_or_404(UserModel, id=id)
    user.delete()
    messages.success(request, "L'utilisateur a été supprimé avec succès.")  
    return redirect('user:index')

def login(request):

    return render(request, "login.html")   
 

src/templates/user/add_user.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
 
{% block title %}
    <title>MonEtab - User</title>
{% endblock %}

{% block style %}
    <style>
        .content {
            flex: 1;
            padding: 20px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        h1 {
            margin: 0 0 20px 0;
        }
        form {
            width: 30%;
        }
        label {
            display: block;
            margin-bottom: 8px;
        }
        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }
        .button {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-right: 10px;
        }
        .cancel {
            background-color: #FF0000; 
            color: white;
        }
        .save {
            background-color: #28A745; 
            color: white;
        }
    </style>
{% endblock style %}


{% block body %}
    <div class="content">
        <h1>{{ title }}</h1>

        {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}

        <form class="" method="post" novalidate>
            {% csrf_token %} 
            {{ form|crispy }}  
            <button type="submit" class="button save">{{ submit_value }}</button>
            <button type="reset"> Annuler</button>
        </form>

        {% if form.errors %}
            <div class="error">
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
{% endblock body %}

src/templates/user/index.html
{% extends "base.html" %}

{% block style %}
    <style>
         .content {
            flex: 1;
            padding: 20px;
        }
        h1 {
            margin: 0 0 20px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background: white;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background: #f2f2f2;
        }
        .button {
            padding: 5px 10px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .edit {
            background-color: #FFA500; 
            color: #575552;
        }
    </style>
{% endblock style %}

{% block title %}
<title>MonEtab - User</title>
{% endblock %}

{% block body %}
<div class="content_user">
    <h1>Utilisateurs (2)</h1>
    <button type="submit"><a href="{% url 'user:add' %}">Ajouter utilisateur</a></button>
    <table>
        <thead>
            <tr>
                <th>Pseudo</th>
                <th>Date de création</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.pseudo }}</td>
                <td>{{ user.date_creation|date:"D d M Y" }}</td>
                <td>
                    <a class="button modify" href="{% url 'user:update' user.id %}">Modifier</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock body %}

src/templates/user/update_user.html
{% extends "base.html" %}

{% block style %}
    <style>
        .content {
            flex: 1;
            padding: 20px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        h1 {
            margin: 0 0 20px 0;
        }
        form {
            /* background: white;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); */
            width: 300px;
        }
        label {
            display: block;
            margin-bottom: 8px;
        }
        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }
        .button {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-right: 10px;
        }
        .cancel {
            background-color: #FF0000; /* red */
            color: white;
        }
        .save {
            background-color: #28A745; /* green */
            color: white;
        }
    </style>
{% endblock style %}

{% block title %}
<title>MonEtab - User</title>
{% endblock %}

{% block body %}
<div class="content">
    <h1>Modifier l'utilisateur - 45678</h1>
    <form>
        <label for="username">Nom d'utilisateur</label>
        <input type="text" id="username" value="admin" disabled>
        
        <label for="old-password">Ancien mot de passe</label>
        <input type="password" id="old-password" required>
        
        <label for="new-password">Nouveau mot de passe</label>
        <input type="password" id="new-password" required>
        
        <label for="confirm-password">Confirmer nouveau mot de passe</label>
        <input type="password" id="confirm-password" required>
        
        <div>
            <button type="button" class="button cancel">Annuler</button>
            <button type="submit" class="button save">Enregistrer</button>
        </div>
    </form>
</div>
{% endblock body %}