src/dashboard/urls.py
from django.urls import path
from .views import index, report

app_name = 'dashboard'

urlpatterns = [
    path('', index, name='index'),
    path('report/', report, name='report'),
] 

src/student/urls.py
from django.urls import path
from .views import index_student, add_student, update_student, delete_student

app_name = 'student'

urlpatterns = [
    path('', index_student, name='index'),
    path('add-student', add_student, name='add'),
    path('update-student/<int:id>', update_student, name='update'),
    path('delete-student/<int:id>', delete_student, name='delete'),
    
] 

src/teacher/urls.py
from django.urls import path
from .views import index_teacher, add_teacher, update_teacher, delete_teacher

app_name = 'teacher'

urlpatterns = [
    path('', index_teacher, name='index'),
    path('add-teacher', add_teacher, name='add'),
    path('update-teacher/<int:id>', update_teacher, name='update'),
    path('delete-teacher/<int:id>', delete_teacher, name='delete'),
] 

src/user/urls.py
from django.urls import path
from .views import index_user, add_user, update_user, delete_user

app_name = 'user'

urlpatterns = [
    path('', index_user, name='index'),
    path('add-user', add_user, name='add'),
    path('update-user/<int:id>', update_user, name='update'),
    path('delete-user/<int:id>', delete_user, name='delete'),
] 

src/webSite/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import login

urlpatterns = [
    path('', login, name='login'), 
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')), 
    path('student/', include('student.urls')), 
    path('teacher/', include('teacher.urls')), 
    path('user/', include('user.urls')), 
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        {% block title %}
            <title>MonEtab -</title>
        {% endblock %}
        {% block style %}

        {% endblock style %}
    </head>

    <body>
        {% include 'sidebar.html' %}

        {% block body %}

        {% endblock body %}

        {% block script %}
          
        {% endblock script %}
    </body>
</html>

src/templates/login.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon Etab - Page de Connexion</title>
    <style>
        body {
            background-color: #4c545a; 
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            font-family: Arial, sans-serif;
        }
        .login {
            background: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            text-align: center;
            color: #464a4d;
            height: 50%;
            width: 25%;
        }
        h1 {
            margin-bottom: 20px;
        }
        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 5px;
            margin: 10px 0;
            border: solid 3px dark;
            border-radius: 5px;
            color: #535A5D;
        }
        button {
            background-color: #535A5D;
            width: 100%;
            padding: 5px;
            margin: 10px 0;
            border: solid 5px dark;
            border-radius: 5px;
            box-shadow: 10 110 10px rgba(0, 0, 0, 0.5);
        }
        button:hover {
            background-color: #0056b3;
            color: azure;
        }
    </style>
</head>
<body>
    <div class="login">
        <h1>Mon Etab</h1>
        <input type="text" placeholder="Identifiant" required value="admin">
        <input type="password" placeholder="Mot de passe" required value="admin">
        <button onclick="login()">Connexion</button>
    </div>

    <script>
        function login() {
            location.href = '/dashboard';
        }
    </script>
</body>
</html>

src/templates/sidebar.html
{% load static %}
<div class="sidebar">
    <img src="{% static 'img/logo_etab.jpg' %}" class="img" height="40px" width="50px" alt="logo">
    <h2>Mon Etab</h2>
    <hr>
    <a href="{% url 'dashboard:index' %}"> <i class="fas fa-tachometer-alt"></i> Tableau de bord</a>
    <a href="{% url 'student:index' %}"> <i class="fas fa-user-graduate"></i> Élèves</a>
    <a href="{% url 'teacher:index' %}"> <i class="fas fa-chalkboard-teacher"></i> Professeurs</a>
    <a href="{% url 'user:index' %}"> <i class="fas fa-users"></i> Utilisateurs</a>
    <a href="{% url 'dashboard:report' %}"> <i class="fas fa-file-alt"></i> Rapport</a>
    <div class="logout">
        <hr>
        <a href="#"> <i class="fas fa-sign-out-alt"></i> Déconnexion</a>
    </div>
</div>