src/student/urls.py
from django.urls import path
from .views import index_student, add_student, update_student, delete_student

app_name = 'student'

urlpatterns = [
    path('', index_student, name='index'),
    path('add-student', add_student, name='add'),
    path('update-student/<int:id>', update_student, name='update'),
    path('delete-student/<int:id>', delete_student, name='delete'),
    
] 

src/user/urls.py
from django.urls import path
from .views import index_user, add_user, update_user, delete_user

app_name = 'user'

urlpatterns = [
    path('', index_user, name='index'),
    path('add-user', add_user, name='add'),
    path('update-user/<int:id>', update_user, name='update'),
    path('delete-user/<int:id>', delete_user, name='delete'),
] 

src/webSite/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import login

urlpatterns = [
    path('', login, name='login'), 
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')), 
    path('student/', include('student.urls')), 
    path('teacher/', include('teacher.urls')), 
    path('user/', include('user.urls')), 
]

src/student/models.py
from django.db import models
import datetime

# Create your models here.

CLASSROOM_CHOICES = (
    ('Tle', 'Terminale'),
    ('1ere', 'Première'),
    ('2nde', 'Deuxième'),
    ('3eme', 'Troisième'),
    ('4eme', 'Quatrième'),
    ('5eme', 'Cinquième'),
    ('6eme', 'Sixième'),
)

GENDER_CHOICES = (
    ('H', 'Homme'),
    ('F', 'Femme'),
)

class StudentModel(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=100)
    registration_number = models.CharField(max_length=30, unique=True)
    birth_date = models.DateField()
    classroom = models.CharField(max_length=20, choices=CLASSROOM_CHOICES)
    phone = models.CharField(max_length=10, unique=True, blank=True)
    city = models.CharField(max_length=30) 
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='Homme')

    def __str__(self) -> str:
        return f"{self.registration_number} - {self.first_name} {self.last_name}"
    
    @property
    def age(self):
        today = datetime.date.today()
        age = today.year - self.birth_date.year - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))
        return age
    
    class Meta:
        ordering = ['-id']
        verbose_name = 'Élève'
        verbose_name_plural = 'Élèves'

src/student/forms.py
from django import forms
from .models import StudentModel

class StudentForm(forms.ModelForm):

    class Meta:
        model = StudentModel
        fields = "__all__"
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prénom'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom'}),
            'registration_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Numéro Matricule'}),
            'birth_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'classroom': forms.Select(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Téléphone'}),
            'city': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ville'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
        }

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if not phone.isdigit():
            raise forms.ValidationError("Le téléphone doit contenir uniquement des chiffres.")
        return phone 

# class StudentForm(forms.Form):
#     registration_number = forms.CharField(label="Matricule", max_length=20, strip=True, required=True)
#     first_name = forms.CharField(label="Nom", max_length=20, strip=True, required=True)
#     last_name = forms.CharField(label="Prénoms", max_length=50, strip=True, required=True)
#     birth_date = forms.DateField(label="Date de naissance", required=True, widget=forms.SelectDateWidget())
#     city = forms.CharField(label="Ville", max_length=30, strip=True, required=True)
#     phone = forms.CharField(label="Téléphone", max_length=10, strip=True, required=True)
#     classroom = forms.CharField(label="Classe", max_length=20, strip=True, required=True)

#     def clean_phone(self):
#         phone = self.cleaned_data.get('phone')
#         if not phone.isdigit():
#             raise forms.ValidationError("Le téléphone doit contenir uniquement des chiffres.")
#         return phone

src/student/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib import messages

from .models import StudentModel
from .forms import StudentForm

# Create your views here.

def index_student(request):
    students_list =  StudentModel.objects.all()

    paginator = Paginator(students_list, 10)  
    page_number = request.GET.get('page')
    students = paginator.get_page(page_number)

    context = {
        'students': students
    }

    return render(request, "student/index.html", context) 

# def add_student(request):

#     if request.method == "POST":
#         form = StudentForm(request.POST)
#         if form.is_valid():
#             Student.objects.create(
#                 registration_number=form.cleaned_data['registration_number'],
#                 first_name=form.cleaned_data['first_name'],
#                 last_name=form.cleaned_data['last_name'],
#                 birth_date=form.cleaned_data['birth_date'],
#                 city=form.cleaned_data['city'],
#                 phone=form.cleaned_data['phone'],
#                 classroom=form.cleaned_data['classroom']
#                 )
#             return redirect("student:index") 
#     else:
#         form = StudentForm()

#     return render(request, "student/add_student.html", {'form': form}) 


def add_student(request):
    context = {
        'title': 'Ajouter élève',
        'submit_value': 'Ajouter'
    }

    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "L'élève a été ajouté avec succès.")
            return redirect("student:index")
        else:
            print('erreur')
            messages.error(request, "Erreur dans le formulaire. Veuillez vérifier les champs.")
    else:
        form = StudentForm()
    context['form'] = form

    return render(request, "student/add_student.html", context) 

def update_student(request, id):

    student = StudentModel.objects.get(id = id)
    context = {
        'title': 'Modifier le professeur',
        'submit_value': 'Modifier'
    }
    if request.method == "POST":
        student_form = StudentForm(request.POST, instance=student)
        if student_form.is_valid():
            student_form.save()
            return redirect("student:index")
        else:
            print("formulaire erroné")
            messages.error(request, "Erreur dans le formulaire. Veuillez vérifier les champs.")


    student_form = StudentForm(instance=student)
    context['form'] = student_form

    return render(request, "student/add_student.html", context) 
 
def delete_student(request, id):
    student = get_object_or_404(StudentModel, id=id)
    student.delete()

    return redirect('student:index')
    

src/templates/student/add_student.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>MonEtab - Student</title>
{% endblock %}

{% block style %}
    <style>
            .content {
                flex: 1;
                padding: 20px;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
            }
            h1 {
                margin: 0 0 20px 0;
            }
            form {
                width: 50%;
            }
            label {
                display: inline;
                margin-bottom: 8px;
            }
            input[type="text"],
            input[type="date"],
            select {
                width: 100%;
                padding: 10px;
                margin-bottom: 20px;
                border-radius: 5px;
                border: 1px solid #ccc;
            }
            .button {
                padding: 10px 20px;
                border: none;
                border-radius: 5px;
                cursor: pointer;
                margin-right: 10px;
            }
            .cancel {
                background-color: #FF0000; 
                color: white;
            }
            .save {
                background-color: #28A745; 
                color: white;
            }
            .row {
                display: flex;
                justify-content: space-between;
                margin-bottom: 15px;
            }
            .col {
                flex: 0 0 48%;
            }
    </style>  
{% endblock style %}


{% block body%}

<div class="content">
    <h1>{{ title }}</h1>
    
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}  
            <button type="submit" class="button save">{{ submit_value }}</button>
    </form>

    {% if form.errors %}
        <div class="error">
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

</div>
{% endblock body %}

src/templates/student/index.html
{% extends 'base.html' %}

{% block style %}
    <style>
                .content {
            flex: 1;
            padding: 20px;
        }
        h1 {
            margin: 0 0 20px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background: white;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background: #f2f2f2;
        }
        .button {
            padding: 5px 10px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .modify {
            background-color: #FFA500; 
            color: #575552;
        }
        .delete {
            background-color: #FF0000; 
            color: #d1cdc5;
        }
        .modal {
            display: none;
            position: fixed;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5);
            justify-content: center;
            align-items: center;
        
        }
        .modal-content {
            background: white;
            padding: 10px;
            border-radius: 20px;
            text-align: center;
        }
    </style>      
{% endblock style %}

{% block title %}
<title>MonEtab - Student</title>
{% endblock %}

{% block body%}

<div class="content_student">
    <h1>Élèves (2)</h1>
    <button><a href="{% url 'student:add' %}">Ajouter eleve</a></button>
    <table>
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Genre</th>
                <th>Classe</th>
                <th>Matricule</th>
                <th>Âge</th>
                <th>Téléphone</th>
                <th>Ville</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.gender }}</td>
                <td>{{ student.classroom }}</td>
                <td>{{ student.registration_number }}</td>
                <td>{{ student.age }} ans</td>
                <td>{{ student.phone }}</td>
                <td>{{ student.city }}</td>
                <td>
                    <a class="button modify" href="{% url 'student:update' student.id %}">Modifier</a>
                    <button class="button delete" data-id="{{student.id}}" onclick="showModal(this)">Supprimer</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="modal" id="modal">
        <div class="modal-content"> 
            <h2>ATTENTION !!</h2>
            <p>Voulez-vous vraiment supprimer cet élève ?</p>
            <button onclick="closeModal()">Non</button>
            <button onclick="confirmDelete()">Oui</button>
        </div>
    </div>
</div>

{% endblock body %}

{% block script %}

<script>
    let studentId;

    function showModal(buttonElement) {
        studentId = buttonElement.getAttribute('data-id');  
        document.getElementById('modal').style.display = 'flex';  
    }

    function closeModal() {
        document.getElementById('modal').style.display = 'none';     
    }

    function confirmDelete() {
        closeModal();
        window.location.href = "{% url 'student:delete' 0 %}".replace(0, studentId);
    }
</script>

{% endblock script %}

src/templates/student/update_student.html
{% extends 'base.html' %}

{% block style %}
        <style>
             .content {
            flex: 1;
            padding: 20px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        h1 {
            margin: 0 0 20px 0;
        }
        form {
            /* background: white;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); */
            width: 400px;
        }
        label {
            display: block;
            margin-bottom: 8px;
        }
        input[type="text"],
        input[type="date"],
        input[type="number"],
        select {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }
        .button {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-right: 10px;
        }
        .cancel {
            background-color: #FF0000; /* red */
            color: white;
        }
        .save {
            background-color: #28A745; /* green */
            color: white;
        }
        </style>  
{% endblock style %}

{% block title %}
<title>MonEtab - Student</title>
{% endblock %}

{% block body%}

<div class="content">
    <h1>Modifier l'élève - 245</h1>
    <form>
        <label for="lastname">Nom</label>
        <input type="text" id="lastname" value="KOUAKOU" required>
        
        <label for="firstname">Prénom</label>
        <input type="text" id="firstname" value="Georges" required>

        <label>Genre</label>
        <label><input type="radio" name="gender" value="Homme" required> Homme</label>
        <label><input type="radio" name="gender" value="Femme" required> Femme</label>

        <label for="phone">Téléphone</label>
        <input type="text" id="phone" value="0123456789" required>

        <label for="address">Adresse</label>
        <input type="text" id="address" value="Dakar" required>

        <label for="idNumber">Numéro d'identité</label>
        <input type="text" id="idNumber" value="G0U038737" required>

        <label for="dob">Date de naissance</label>
        <input type="date" id="dob" value="1992-08-12" required>

        <div>
            <button type="button" class="button cancel">Annuler</button>
            <button type="submit" class="button save">Enregistrer</button>
        </div>
    </form>
</div>
{% endblock body %}