src/teacher/urls.py
from django.urls import path
from .views import index_teacher, add_teacher, update_teacher, delete_teacher

app_name = 'teacher'

urlpatterns = [
    path('', index_teacher, name='index'),
    path('add-teacher', add_teacher, name='add'),
    path('update-teacher/<int:id>', update_teacher, name='update'),
    path('delete-teacher/<int:id>', delete_teacher, name='delete'),
] 

src/user/urls.py
from django.urls import path
from .views import index_user, add_user, update_user, delete_user

app_name = 'user'

urlpatterns = [
    path('', index_user, name='index'),
    path('add-user', add_user, name='add'),
    path('update-user/<int:id>', update_user, name='update'),
    path('delete-user/<int:id>', delete_user, name='delete'),
] 

src/webSite/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import login

urlpatterns = [
    path('', login, name='login'), 
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')), 
    path('student/', include('student.urls')), 
    path('teacher/', include('teacher.urls')), 
    path('user/', include('user.urls')), 
]

src/teacher/models.py
from django.db import models
import datetime

# Create your models here.

SUBJECT_CHOICES = (
    ('math', 'Math'),
    ('physique', 'Physique'),
    ('anglais', 'Anglais'),
    ('svt', 'SVT'),
    ('histoire', 'Histoire'),
    ('français', 'Français'),
)

VACCANT_CHOICE = (
    ('OUI', 'OUI'),
    ('NON', 'NON'),
)

class TeacherModel(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField()
    is_vacant = models.CharField(max_length=20, choices=VACCANT_CHOICE) 
    city = models.CharField(max_length=30)
    phone = models.PositiveIntegerField(unique=True, blank=True)
    subject_taught = models.CharField(max_length=20, choices=SUBJECT_CHOICES)  
    next_class = models.CharField(max_length=50)
    next_meeting_topic = models.CharField(max_length=100)  

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.subject_taught}"

    @property
    def age(self):
        today = datetime.date.today()
        age = today.year - self.birth_date.year - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))
        return age
    
    class Meta:
        ordering = ['-id']
        verbose_name = 'Professeur'
        verbose_name_plural = 'Professeurs'

src/teacher/forms.py
from django import forms

from .models import TeacherModel

class TeacherForm(forms.ModelForm):

    class Meta:
        model = TeacherModel
        fields  = "__all__" 
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prénom'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom'}),
            'next_class': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prochain cours'}),
            'birth_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'subject_taught': forms.Select(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Téléphone'}),
            'city': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ville'}),
            'is_vacant': forms.Select(attrs={'class': 'form-control', 'type':'radio'}),
            'next_meeting_topic': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Sujet prochaine réunion'}),
        }

    # def clean_phone(self):
    #     phone = self.cleaned_data.get('phone')
    #     if not phone.isdigit():
    #         raise forms.ValidationError("Le téléphone doit contenir uniquement des chiffres.")
    #     return phone 

# class TeacherForm(forms.Form):
#     first_name = forms.CharField(label="Nom", max_length=20, strip=True, required=True)
#     last_name = forms.CharField(label="Prénoms", max_length=50, strip=True, required=True)
#     birth_date = forms.DateField(label="Date de naissance", required=True, widget=forms.SelectDateWidget())
#     city = forms.CharField(label="Ville", max_length=30, strip=True, required=True)
#     phone = forms.CharField(label="Téléphone", max_length=10, strip=True, required=True)
#     subject_taught = forms.CharField(label="Matière enseignée", max_length=30, strip=True, required=True)
#     next_class = forms.CharField(label="Prochain cours", max_length=30, strip=True, required=True)
#     next_meeting_topic = forms.CharField(label="Sujet de la prochaine réunion", max_length=30, strip=True, required=True)
#     is_vacant = forms.BooleanField(label="Est vacant ?", required=False, initial=True)

#     def clean_phone(self):
#         phone = self.cleaned_data.get('phone')
#         if not phone.isdigit():
#             raise forms.ValidationError("Le téléphone doit contenir uniquement des chiffres.")
#         return phone

src/teacher/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib import messages

from .models import TeacherModel
from .forms import TeacherForm

# Create your views here.

def index_teacher(request):

    teacher_list =  TeacherModel.objects.all()

    paginator = Paginator(teacher_list, 10)  
    page_number = request.GET.get('page')
    teachers = paginator.get_page(page_number)

    context = {
        'teachers': teachers
    }
    return render(request, "teacher/index.html", context) 

# def add_teacher(request):
#     forms = TeacherForm()

#     if request.method == "POST":
#         form = TeacherForm(request.POST)
#         if form.is_valid():
#             Teacher.objects.create(
#                 first_name=form.cleaned_data['first_name'],
#                 last_name=form.cleaned_data['last_name'],
#                 birth_date=form.cleaned_data['birth_date'],
#                 city=form.cleaned_data['city'],
#                 phone=form.cleaned_data['phone'],
#                 subject_taught=form.cleaned_data['subject_taught'],
#                 next_class=form.cleaned_data['next_class'],
#                 next_meeting_topic=form.cleaned_data['next_meeting_topic'],
#                 is_vacant=form.cleaned_data['is_vacant']
#                 )
#             return redirect("teacher:index") 
#     else:
#         form = TeacherForm()

#     context = {
        
#     }

#     return render(request, "teacher/add_teacher.html", {'form': form, 'forms': forms}) 


def add_teacher(request):
    context = {
        'title': 'Ajouter professeur',
        'submit_value': 'Ajouter'
    }

    if request.method == "POST":
        form = TeacherForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Le professeur a été ajouté avec succès.")
            return redirect("teacher:index")
        else:
            print('erreur')
            messages.error(request, "Erreur dans le formulaire. Veuillez vérifier les champs.")
    else:
        form = TeacherForm()
    context['form'] = form

    return render(request, "teacher/add_teacher.html", context) 
 

def update_teacher(request, id):

    teacher = TeacherModel.objects.get(id = id)
    context = {
        'title': 'Modifier le professeur',
        'submit_value': 'Modifier'
    }
    if request.method == "POST":
        teacher_form = TeacherForm(request.POST, instance=teacher)
        if teacher_form.is_valid():
            teacher_form.save()
            return redirect("teacher:index")
        else:
            print("formulaire erroné")
            messages.error(request, "Erreur dans le formulaire. Veuillez vérifier les champs.")


    teacher_form = TeacherForm(instance=teacher)
    context['form'] = teacher_form

    return render(request, "teacher/add_teacher.html", context) 
 
def delete_teacher(request, id):
    teacher = get_object_or_404(TeacherModel, id=id)
    teacher.delete()

    return redirect('teacher:index') 

src/templates/teacher/add_teacher.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    <title>MonEtab - Teacher</title>
{% endblock %}

{% block style %}
    <style>
        .content {
            flex: 1;
            padding: 20px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        h1 {
            margin: 0 0 20px 0;
        }
        form {
            /* background: white; */
            /* padding: 50px; */
            /* border-radius: 5px; */
            /* box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); */
            width: 50%;
        }
        label {
            display: inline;
            margin-bottom: 8px;
        }
        input[type="text"],
        input[type="date"],
        select {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }
        .button {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-right: 10px;
        }
        .cancel {
            background-color: #FF0000; 
            color: white;
        }
        .save {
            background-color: #28A745; 
            color: white;
        }
        .row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 15px;
        }
        .col {
            flex: 0 0 48%;
        }
    </style>
{% endblock style %}


{% block body %}
    <div class="content">
        <h1>{{ title }}</h1>

        {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}

        <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="button save">{{ submit_value }}</button>
        </form>

        {% if form.errors %}
            <div class="error">
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    
    </div>
{% endblock body %}

src/templates/teacher/index.html
{% extends 'base.html' %}

{% block style %}
    <style>
                .content {
            flex: 1;
            padding: 20px;
        }
        h1 {
            margin: 0 0 20px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background: white;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background: #f2f2f2;
        }
        .button {
            padding: 5px 10px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .edit {
            background-color: #FFA500; 
            color: #575552;
        }
        .delete {
            background-color: #FF0000; 
            color: #d1cdc5;
        }
        .modal {
            display: none;
            position: fixed;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5);
            justify-content: center;
            align-items: center;
        
        }
        .modal-content {
            background: white;
            padding: 10px;
            border-radius: 20px;
            text-align: center;
        }
    </style>
{% endblock style %}

{% block title %}
<title>MonEtab - Teacher</title>
{% endblock %}

{% block body%}

<div class="content">
    <h1>Professeurs (2)</h1>
    <button type="button"><a href="{% url 'teacher:add' %}">Ajouter professeur</a></button>
    <table>
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Matière</th>
                <th>Vacant</th>
                <th>Âge</th>
                <th>Téléphone</th>
                <th>Ville</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for teacher in teachers %}
            <tr>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.subject_taught }}</td>
                <td>{{ teacher.is_vacant }}</td>
                <td>{{ teacher.age }} ans</td>
                <td>{{ teacher.phone }}</td>
                <td>{{ teacher.city }}</td>
                <td>
                    <a class="button modify" href="{% url 'teacher:update' teacher.id %}">Modifier</a>
                    <button class="button delete" data-id="{{teacher.id}}" onclick="showModal(this)">Supprimer</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="modal" id="modal">
        <div class="modal-content">
            <h2>ATTENTION !!</h2>
            <p>Voulez-vous vraiment supprimer ce professeur ?</p>
            <button onclick="closeModal()">Non</button>
            <button onclick="confirmDelete()">Oui</button>
        </div>
    </div>
</div>
{% endblock body %}

{% block script %}
<script>
    let teacherId;

    function showModal(buttonElement) {
        teacherId = buttonElement.getAttribute('data-id');  
        document.getElementById('modal').style.display = 'flex';  
    }

    function closeModal() {
        document.getElementById('modal').style.display = 'none';     
    }

    function confirmDelete() {
        closeModal();
        window.location.href = "{% url 'teacher:delete' 0 %}".replace(0, teacherId);
    }
</script>

{% endblock script %}

src/templates/teacher/update_teacher.html
{% extends "base.html" %}

{% block style %}
    <style>
                .content {
            flex: 1;
            padding: 20px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        h1 {
            margin: 0 0 20px 0;
        }
        form {
            /* background: white;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); */
            width: 400px;
        }
        label {
            display: block;
            margin-bottom: 8px;
        }
        input[type="text"],
        input[type="date"],
        select {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }
        .button {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-right: 10px;
        }
        .cancel {
            background-color: #FF0000; /* red */
            color: white;
        }
        .save {
            background-color: #28A745; /* green */
            color: white;
        }
    </style>
{% endblock style %}

{% block title %}
<title>MonEtab - Teacher</title>
{% endblock %}

{% block body %}
<div class="content">
    <h1>Modifier le professeur - 738</h1>
    <form>
        <label for="lastname">Nom</label>
        <input type="text" id="lastname" required>
        
        <label for="firstname">Prénom</label>
        <input type="text" id="firstname" required>

        <label for="subject">Matière</label>
        <select id="subject" required>
            <option value="anglais">Anglais</option>
            <option value="maths">Mathématiques</option>
            <option value="sciences">Sciences</option>
        </select>

        <label for="phone">Téléphone</label>
        <input type="text" id="phone" required>

        <label>Genre</label>
        <label><input type="radio" name="gender" value="Homme" required> Homme</label>
        <label><input type="radio" name="gender" value="Femme" required> Femme</label>

        <label for="dob">Date de naissance</label>
        <input type="date" id="dob" required>

        <div>
            <button type="button" class="button cancel">Annuler</button>
            <button type="submit" class="button save">Enregistrer</button>
        </div>
    </form>
</div>
{% endblock body %}